class_name PlayerTuning
extends RefCounted

const WALK_SPEED := 4.5
const SPRINT_SPEED := 6.5
const CROUCH_SPEED := 2.5
const MEDIUM_CARRY_SPEED_FACTOR := 0.75
const MEDIUM_PROP_MIN_MASS := 10.0
const GROUND_ACCELERATION := 25.0
const AIR_ACCELERATION := 8.0
const GRAVITY := 20.0
const JUMP_HEIGHT := 1.35
const JUMP_VELOCITY := sqrt(2.0 * GRAVITY * JUMP_HEIGHT)
const COYOTE_TIME := 0.12
const JUMP_BUFFER_TIME := 0.12
const STANDING_HEIGHT := 1.5
const CROUCHED_HEIGHT := 0.95
const CAPSULE_RADIUS := 0.28
const PREDICTION_HISTORY_TICKS := 60
const KNOCKDOWN_MIN_TIME := 0.6
const KNOCKDOWN_DURATION := 1.4
const GRAB_RANGE := 1.5
const GRAB_MIN_MASS := 2.0
const GRAB_MAX_MASS := 25.0
const GRAB_HOLD_DISTANCE := 1.0
const GRAB_BREAK_DISTANCE := 2.5
const GRAB_MIN_FORWARD_DOT := 0.25
const GRAB_SPRING_STRENGTH := 180.0
const GRAB_SPRING_DAMPING := 24.0
const GRAB_MAX_FORCE := 420.0
